[2024-11-04T16:27:19.590+0100] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: gcs_to_bq_custom_operator_dag.load_vbak_to_bq manual__2024-11-04T15:27:17.879290+00:00 [queued]>
[2024-11-04T16:27:19.611+0100] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: gcs_to_bq_custom_operator_dag.load_vbak_to_bq manual__2024-11-04T15:27:17.879290+00:00 [queued]>
[2024-11-04T16:27:19.611+0100] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-11-04T16:27:19.611+0100] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-11-04T16:27:19.611+0100] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-11-04T16:27:19.632+0100] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_vbak_to_bq> on 2024-11-04 15:27:17.879290+00:00
[2024-11-04T16:27:19.644+0100] {standard_task_runner.py:55} INFO - Started process 2482 to run task
[2024-11-04T16:27:19.650+0100] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gcs_to_bq_custom_operator_dag', 'load_vbak_to_bq', 'manual__2024-11-04T15:27:17.879290+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/extraction_dag.py', '--cfg-path', '/tmp/tmp1ewjwp00']
[2024-11-04T16:27:19.654+0100] {standard_task_runner.py:83} INFO - Job 141: Subtask load_vbak_to_bq
[2024-11-04T16:27:19.763+0100] {task_command.py:389} INFO - Running <TaskInstance: gcs_to_bq_custom_operator_dag.load_vbak_to_bq manual__2024-11-04T15:27:17.879290+00:00 [running]> on host db3b4b82dec0
[2024-11-04T16:27:19.874+0100] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Admin
AIRFLOW_CTX_DAG_ID=gcs_to_bq_custom_operator_dag
AIRFLOW_CTX_TASK_ID=load_vbak_to_bq
AIRFLOW_CTX_EXECUTION_DATE=2024-11-04T15:27:17.879290+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-04T15:27:17.879290+00:00
[2024-11-04T16:27:20.195+0100] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extraction_dag.py", line 30, in load_data_to_bq
    load_job.result()  # Wait for the job to complete
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.Forbidden: 403 Access Denied: BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform write scope.
[2024-11-04T16:27:20.211+0100] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_to_bq_custom_operator_dag, task_id=load_vbak_to_bq, execution_date=20241104T152717, start_date=20241104T152719, end_date=20241104T152720
[2024-11-04T16:27:20.230+0100] {standard_task_runner.py:105} ERROR - Failed to execute job 141 for task load_vbak_to_bq (403 Access Denied: BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform write scope.; 2482)
[2024-11-04T16:27:20.263+0100] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-11-04T16:27:20.308+0100] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
