[2024-10-28T18:15:12.855+0100] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: airbyte_dag.run_airbyte_container manual__2024-10-28T17:15:11.322337+00:00 [queued]>
[2024-10-28T18:15:12.884+0100] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: airbyte_dag.run_airbyte_container manual__2024-10-28T17:15:11.322337+00:00 [queued]>
[2024-10-28T18:15:12.884+0100] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-10-28T18:15:12.885+0100] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-10-28T18:15:12.885+0100] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-10-28T18:15:12.910+0100] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): run_airbyte_container> on 2024-10-28 17:15:11.322337+00:00
[2024-10-28T18:15:12.919+0100] {standard_task_runner.py:55} INFO - Started process 654 to run task
[2024-10-28T18:15:12.927+0100] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'airbyte_dag', 'run_airbyte_container', 'manual__2024-10-28T17:15:11.322337+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/airbyte_dag.py', '--cfg-path', '/tmp/tmpcc7ahwic']
[2024-10-28T18:15:12.931+0100] {standard_task_runner.py:83} INFO - Job 21: Subtask run_airbyte_container
[2024-10-28T18:15:13.065+0100] {task_command.py:389} INFO - Running <TaskInstance: airbyte_dag.run_airbyte_container manual__2024-10-28T17:15:11.322337+00:00 [running]> on host a5fd28bf0c7a
[2024-10-28T18:15:13.240+0100] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Admin
AIRFLOW_CTX_DAG_ID=airbyte_dag
AIRFLOW_CTX_TASK_ID=run_airbyte_container
AIRFLOW_CTX_EXECUTION_DATE=2024-10-28T17:15:11.322337+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-28T17:15:11.322337+00:00
[2024-10-28T18:15:13.270+0100] {docker.py:284} INFO - Starting docker container from image europe-west1-docker.pkg.dev/eltl-pipeline-project/docker-hub/airbyte-app:latest
[2024-10-28T18:15:13.277+0100] {docker.py:295} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-10-28T18:15:13.773+0100] {docker.py:354} INFO - Error: Unable to access jarfile /airbyte/airbyte-worker.jar
Error: Unable to access jarfile /airbyte/airbyte-webapp.jar
[2024-10-28T18:15:13.775+0100] {docker.py:354} INFO - Error: Unable to access jarfile /airbyte/airbyte-server.jar
[2024-10-28T18:15:13.975+0100] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=airbyte_dag, task_id=run_airbyte_container, execution_date=20241028T171511, start_date=20241028T171512, end_date=20241028T171513
[2024-10-28T18:15:14.024+0100] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-10-28T18:15:14.098+0100] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
