[2024-11-04T17:56:55.355+0100] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: gcs_to_bq_with_quality_checks.check_vbak_quality manual__2024-11-04T16:51:41.606183+00:00 [queued]>
[2024-11-04T17:56:55.390+0100] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: gcs_to_bq_with_quality_checks.check_vbak_quality manual__2024-11-04T16:51:41.606183+00:00 [queued]>
[2024-11-04T17:56:55.391+0100] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-11-04T17:56:55.391+0100] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2024-11-04T17:56:55.391+0100] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-11-04T17:56:55.424+0100] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): check_vbak_quality> on 2024-11-04 16:51:41.606183+00:00
[2024-11-04T17:56:55.440+0100] {standard_task_runner.py:55} INFO - Started process 22318 to run task
[2024-11-04T17:56:55.448+0100] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gcs_to_bq_with_quality_checks', 'check_vbak_quality', 'manual__2024-11-04T16:51:41.606183+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/extraction_dag_with_dq_checks.py', '--cfg-path', '/tmp/tmpct0is7dv']
[2024-11-04T17:56:55.452+0100] {standard_task_runner.py:83} INFO - Job 170: Subtask check_vbak_quality
[2024-11-04T17:56:55.577+0100] {task_command.py:389} INFO - Running <TaskInstance: gcs_to_bq_with_quality_checks.check_vbak_quality manual__2024-11-04T16:51:41.606183+00:00 [running]> on host e0d728679b7b
[2024-11-04T17:56:55.737+0100] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Admin
AIRFLOW_CTX_DAG_ID=gcs_to_bq_with_quality_checks
AIRFLOW_CTX_TASK_ID=check_vbak_quality
AIRFLOW_CTX_EXECUTION_DATE=2024-11-04T16:51:41.606183+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-04T16:51:41.606183+00:00
[2024-11-04T17:56:55.941+0100] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extraction_dag_with_dq_checks.py", line 67, in validate_data_quality
    query_job = client.query(query, job_config=job_config)
NameError: name 'query' is not defined
[2024-11-04T17:56:55.959+0100] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=gcs_to_bq_with_quality_checks, task_id=check_vbak_quality, execution_date=20241104T165141, start_date=20241104T165655, end_date=20241104T165655
[2024-11-04T17:56:55.987+0100] {standard_task_runner.py:105} ERROR - Failed to execute job 170 for task check_vbak_quality (name 'query' is not defined; 22318)
[2024-11-04T17:56:56.023+0100] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-11-04T17:56:56.050+0100] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
