[2024-11-04T17:51:52.964+0100] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: gcs_to_bq_with_quality_checks.check_vbak_quality manual__2024-11-04T16:51:41.606183+00:00 [queued]>
[2024-11-04T17:51:52.987+0100] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: gcs_to_bq_with_quality_checks.check_vbak_quality manual__2024-11-04T16:51:41.606183+00:00 [queued]>
[2024-11-04T17:51:52.987+0100] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-11-04T17:51:52.987+0100] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-11-04T17:51:52.987+0100] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-11-04T17:51:53.011+0100] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): check_vbak_quality> on 2024-11-04 16:51:41.606183+00:00
[2024-11-04T17:51:53.024+0100] {standard_task_runner.py:55} INFO - Started process 18436 to run task
[2024-11-04T17:51:53.031+0100] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'gcs_to_bq_with_quality_checks', 'check_vbak_quality', 'manual__2024-11-04T16:51:41.606183+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/extraction_dag_with_dq_checks.py', '--cfg-path', '/tmp/tmp88g86oad']
[2024-11-04T17:51:53.034+0100] {standard_task_runner.py:83} INFO - Job 169: Subtask check_vbak_quality
[2024-11-04T17:51:53.134+0100] {task_command.py:389} INFO - Running <TaskInstance: gcs_to_bq_with_quality_checks.check_vbak_quality manual__2024-11-04T16:51:41.606183+00:00 [running]> on host e0d728679b7b
[2024-11-04T17:51:53.246+0100] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Admin
AIRFLOW_CTX_DAG_ID=gcs_to_bq_with_quality_checks
AIRFLOW_CTX_TASK_ID=check_vbak_quality
AIRFLOW_CTX_EXECUTION_DATE=2024-11-04T16:51:41.606183+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-04T16:51:41.606183+00:00
[2024-11-04T17:51:53.407+0100] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extraction_dag_with_dq_checks.py", line 67, in validate_data_quality
    query_job = client.query(query, job_config=job_config)
NameError: name 'query' is not defined
[2024-11-04T17:51:53.425+0100] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_to_bq_with_quality_checks, task_id=check_vbak_quality, execution_date=20241104T165141, start_date=20241104T165152, end_date=20241104T165153
[2024-11-04T17:51:53.448+0100] {standard_task_runner.py:105} ERROR - Failed to execute job 169 for task check_vbak_quality (name 'query' is not defined; 18436)
[2024-11-04T17:51:53.489+0100] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-11-04T17:51:53.530+0100] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
